---
apiVersion: v1
data:
  k8s-workload-registrar.conf: |-
    log_level = "debug"
    trust_domain = "example.org"
    agent_socket_path = "/run/spire/sockets/agent.sock"
    server_socket_path = "/tmp/spire-server/private/api.sock"
    cluster = "nsm-cluster"
    pod_controller = true
    add_svc_dns_names = true
    mode = "crd"
    webhook_enabled = true
    identity_template = "ns/{{ printf "{{.Pod.Namespace}}" }}/pod/{{ printf "{{.Pod.Name}}" }}"
    identity_template_label = "spiffe.io/spiffe-id"
kind: ConfigMap
metadata:
  name: k8s-workload-registrar
  namespace: spire
