apiVersion: v2
name: kubeslice-controller
description: Kubernetes multi-cluster/cloud fleet management controller using Kubeslice
icon: https://avatars.githubusercontent.com/u/99859346?s=200&v=4
type: application
maintainers:
  - name: Avesha
    email: support@avesha.io
keywords:
- multicloud
- multi cloud
- multitenant
- multitenancy
- multi tenant
- multi tenancy
- federated mesh
- federated clusters
- federated k8s
- federated kubernetes
- cluster sprawl
- sprawl
- namespace sprawl
- network policy
- overlay network
- mesh network
- security
- networking
- infrastructure
- application
kubeVersion: '>= 1.19.0-0'
home: https://avesha.io/products/product-slice
version: 1.3.1
appVersion: 1.3.1
