# Default values for k-native.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubeslice:
  rbacproxy:
    image: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.16.0
  controller:
    logLevel: debug
    rbacResourcePrefix: kubeslice-rbac
    projectnsPrefix: kubeslice
    endpoint:
    image: harbor.saas1.smart-scaler.io/avesha/aveshasystems/kubeslice-controller
    tag: 1.5.0
    pullPolicy: IfNotPresent
  ovpnJob:
    image: harbor.saas1.smart-scaler.io/avesha/aveshasystems/gateway-certs-generator
    tag: 0.9.0
  events:
    disabled: false
