---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-webhook-binding
subjects:
  - kind: ServiceAccount
    name: admission-webhook-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: admission-webhook-role
  apiGroup: rbac.authorization.k8s.io
