apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: nsm-webhook-high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for nsm webhook pods only."