---
apiVersion: v1
kind: Service
metadata:
  name: admission-webhook-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app: admission-webhook-k8s
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: admission-webhook-k8s
