apiVersion: v1
kind: Service
metadata:
  name: nsmgr
  namespace: kubeslice-system
  labels:
    services: nsmgr
spec:
  ports:
  - port: 5001
    name: tcp
  selector:
    app: nsmgr
  internalTrafficPolicy: Local
