---
# Default values for admission-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  nsmw_docker_existingImagePullSecret: "kubeslice-image-pull-secret"
  # IF You dont have existing secret then pass all below values it will create new secret "avesha-docker-ips"
  ## MANDOTORY FIELDS IF EXISTING SECRET NOT PRESENT ##
  nsmw_docker_imagePullSecrets:
    repository: 
    username: ''
    password: ''
    email: ''
  imageRegistry: aveshasystems #ghcr.io/kube-slice
  # Full registry path for harbor images (used in env vars)
  fullImageRegistry: harbor.saas1.smart-scaler.io/avesha/aveshasystems

webhookImageRegistry: cmd-admission-webhook-k8s
webhookImageTag: 1.7.4

nsmInjectContainerImageRegistry: cmd-nsc
nsmInjectContainerImageTag: 1.5.15

nsmInjectInitContainerImageRegistry: cmd-nsc-init
nsmInjectInitContainerImageTag: 1.5.9
nsmInitContainerUpdateDNSConfig: true

# nsm admission webhook ns
nsmNs: kubeslice-nsm-webhook-system
