---
apiVersion: v1
kind: Service
metadata:
  name: k8s-workload-registrar
  namespace: spire
spec:
  type: ClusterIP
  ports:
    - name: webhook
      protocol: TCP
      port: 443
      targetPort: 9443
  selector:
    app: spire-server
