---
apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: ClusterIP
  ports:
    - name: spire-server
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: spire-federation
      port: 8443
      targetPort: 8443
      protocol: TCP
  selector:
    app: spire-server
