apiVersion: v1
kind: Secret
metadata:
  name: kubeslice-hub
  namespace: kubeslice-system 
{{- with .Values.controllerSecret }}
{{- $_ := required "controllerSecret.namespace is required" .namespace }}
{{- $_ := required "controllerSecret.endpoint is required" .endpoint }}
{{- $_ := required "controllerSecret.token is required" .token }}
data:
 {{- toYaml . | nindent 2 }}
{{- end }}
