apiVersion: v2
appVersion: v1.5.1
description: A Helm chart for prometheus pushgateway
home: https://github.com/prometheus/pushgateway
keywords:
- pushgateway
- prometheus
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- email: christian.staude@staffbase.com
  name: cstaud
name: prometheus-pushgateway
sources:
- https://github.com/prometheus/pushgateway
version: 2.0.3
