name: Update Index

on:
  push:
    branches: [ master ]
    paths:
      - '**.tgz'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Helm Installation
        uses: azure/setup-helm@v4

      - name: Update Index
        run: |
          helm repo index .
          git config --global user.email "avesha-bot@aveshasystems.com"
          git config --global user.name "Avesha Bot"
          git add index.yaml
          git commit -m "Update chart index"
          git push
